<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <PlatformTarget>x64</PlatformTarget>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <NoWarn>$(NoWarn);WPF0001</NoWarn>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="LibVLCSharp" Version="3.10.1" />
      <PackageReference Include="LibVLCSharp.WPF" Version="3.10.1" />
      <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.24.4" />
      <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
      <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260627" />
      <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
      <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="Views\MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

</Project>